### ISSUE TITLE
Кринж

### ISSUE THREAD

**Issue by romeros69** [akvamarinel/algo#1]
Маш, ты конечно навалила тут кринжа с алгосами на си плас плас.

**Comment by romeros69** [comment]
Арсений красавчик. Resolved.

**Comment by akvamarinel** [comment]
@romeros69 все лучше, чем кринж на го...........

**Comment by romeros69** [comment]
@akvamarinel ban

**Comment by akvamarinel** [comment]
@romeros69 договорилась с Косяковым, можешь и дальше не ходить на пары!)

**Comment by romeros69** [comment]
@akvamarinel мда трэш

**Comment by romeros69** [comment]
ШАК ОНИЛ

сб, 17 сент. 2022 г. в 23:23, Maria Karaseva ***@***.***>:
